-- Sistem Aplikasi Pemakaman TPU Astana Pratiksha Cianjur
-- Target: Supabase PostgreSQL. V1 schema. Review before production.

create extension if not exists pg_trgm;

create table if not exists public.cemeteries (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  address text,
  google_maps_url text,
  google_maps_query text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.blocks (
  id uuid primary key default gen_random_uuid(),
  cemetery_id uuid not null references public.cemeteries(id) on delete cascade,
  code text not null,
  name text not null,
  capacity integer,
  grid_rows integer,
  grid_columns integer,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  unique(cemetery_id, code)
);

create table if not exists public.graves (
  id uuid primary key default gen_random_uuid(),
  cemetery_id uuid not null references public.cemeteries(id) on delete cascade,
  block_id uuid references public.blocks(id),
  legacy_no integer,
  grave_number integer,
  grave_code text not null unique,
  deceased_name text not null,
  death_date date,
  recorded_date_raw text,
  date_semantics text not null default 'WAFAT',
  heir_name text,
  heir_phone text,
  heir_address text,
  visual_x numeric,
  visual_y numeric,
  visual_row integer,
  visual_column integer,
  photo_path text,
  verify_deceased_name boolean not null default false,
  verify_death_date boolean not null default false,
  verify_heir_name boolean not null default false,
  verify_heir_phone boolean not null default false,
  verify_heir_address boolean not null default false,
  verify_location boolean not null default false,
  verification_status text not null default 'NEEDS_VERIFICATION',
  is_public boolean not null default true,
  transcription_confidence text,
  transcription_notes text,
  source_file text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_graves_name_trgm on public.graves using gin (deceased_name gin_trgm_ops);
create index if not exists idx_graves_block_number on public.graves(block_id, grave_number);
create index if not exists idx_graves_verification on public.graves(verification_status);
create index if not exists idx_graves_public on public.graves(is_public);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

-- Public view deliberately excludes heir/contact fields.
create or replace view public.public_graves as
select
  g.id, g.grave_code, g.deceased_name, g.death_date,
  b.code as block_code, g.grave_number,
  g.visual_x, g.visual_y, g.visual_row, g.visual_column,
  g.photo_path
from public.graves g
left join public.blocks b on b.id = g.block_id
where g.is_public = true;

-- RLS is expected to be enabled and configured during implementation.
-- Public should only read public_graves. Admin/operator CRUD should require authenticated users.
